"""add email verification column

Revision ID: 858e1187357e
Revises: 12ad00d7ad1b
Create Date: 2026-07-17 15:22:58.228910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858e1187357e'
down_revision: Union[str, Sequence[str], None] = '12ad00d7ad1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agriculteur', sa.Column('email_verifie', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agriculteur', 'email_verifie')
    # ### end Alembic commands ###
