"""create parcelle table

Revision ID: ab41ae9f1b1d
Revises: 14fa8ad885ba
Create Date: 2026-07-20 20:45:50.303251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab41ae9f1b1d'
down_revision: Union[str, Sequence[str], None] = '14fa8ad885ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcelle',
    sa.Column('id_parcelle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_exploitation', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_sol', sa.String(length=100), nullable=False),
    sa.Column('type_culture', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_exploitation'], ['exploitation.id_exploitation'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_parcelle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelle')
    # ### end Alembic commands ###
